/**
 * Global Success 4 core vocabulary (numbered cards on
 * `PDF/Global Grade 4/Global success 4 Từ Vựng + Grammar.pdf`).
 * Words + Vietnamese hints aligned with the PDF vocab tables.
 */

export type Lop4VocabItem = {
  word: string;
  hint: string;
  ipa?: string;
};

export type Lop4UnitVocab = {
  unit: number;
  title: string;
  sound?: string;
  words: Lop4VocabItem[];
};

import { LOP4_UNIT_COUNT, LOP4_UNIT_TITLES } from './lop4Units';

export { LOP4_UNIT_COUNT, LOP4_UNIT_TITLES };

export const LOP4_UNIT_VOCAB: Record<number, Lop4UnitVocab> = {
  1: {
    unit: 1,
    title: LOP4_UNIT_TITLES[1],
    words: [
      { word: "America", hint: "nước Mỹ", ipa: "/əˈmerɪkə/" },
      { word: "Australia", hint: "nước Úc", ipa: "/ɒˈstreɪliə/" },
      { word: "Britain", hint: "nước Anh", ipa: "/ˈbrɪtn/" },
      { word: "Japan", hint: "Nhật Bản", ipa: "/dʒəˈpæn/" },
      { word: "France", hint: "nước Pháp", ipa: "/frɑːns/" },
      { word: "Vietnam", hint: "Việt Nam", ipa: "/viːeˈtnɑːm/" },
      { word: "friend", hint: "bạn", ipa: "/frend/" },
      { word: "boy", hint: "cậu bé", ipa: "/bɔɪ/" },
      { word: "girl", hint: "cô bé", ipa: "/ɡɜːl/" },
      { word: "student", hint: "học sinh", ipa: "/ˈstjuːdnt/" },
      { word: "teacher", hint: "giáo viên", ipa: "/ˈtiːtʃə/" },
      { word: "classroom", hint: "phòng học", ipa: "/ˈklɑːsruːm/" },
      { word: "school", hint: "trường học", ipa: "/skuːl/" },
      { word: "play", hint: "chơi", ipa: "/pleɪ/" },
      { word: "study", hint: "học", ipa: "/ˈstʌdi/" },
      { word: "like", hint: "thích", ipa: "/laɪk/" },
      { word: "family", hint: "gia đình", ipa: "/ˈfæmɪli/" },
      { word: "from", hint: "đến từ", ipa: "/frəm/" },
      { word: "country", hint: "đất nước", ipa: "/ˈkʌntri/" },
      { word: "flag", hint: "lá cờ", ipa: "/flæɡ/" },
    ],
  },
  2: {
    unit: 2,
    title: LOP4_UNIT_TITLES[2],
    words: [
      { word: "o'clock", hint: "giờ đúng", ipa: "/əˈklɒk/" },
      { word: "thirty", hint: "ba mươi", ipa: "/ˈθɜːti/" },
      { word: "fifteen", hint: "mười lăm", ipa: "/fɪˈftiːn/" },
      { word: "get up", hint: "thức dậy", ipa: "/ɡet ʌp/" },
      { word: "go to bed", hint: "đi ngủ", ipa: "/ɡəʊ tə bed/" },
      { word: "get up at", hint: "thức dậy lúc", ipa: "/ɡet ʌp æt/" },
      { word: "have breakfast", hint: "ăn sáng", ipa: "/hæv ˈbrekfəst/" },
      { word: "go to school", hint: "đi học", ipa: "/ɡəʊ tə skuːl/" },
      { word: "have lunch", hint: "ăn trưa", ipa: "/hæv lʌntʃ/" },
      { word: "go home", hint: "về nhà", ipa: "/ɡəʊ həʊm/" },
      { word: "do homework", hint: "làm bài tập về nhà", ipa: "/duː ˈhəʊmwɜːk/" },
      { word: "have dinner", hint: "ăn tối", ipa: "/hæv ˈdɪnə/" },
      { word: "watch TV", hint: "xem ti vi", ipa: "/wɒtʃ ˌtiːˈviː/" },
      { word: "listen to music", hint: "nghe nhạc", ipa: "/ˈlɪsn tə ˈmjuːzɪk/" },
      { word: "go to school at", hint: "đi học lúc", ipa: "/ɡəʊ tə skuːl æt/" },
    ],
  },
  3: {
    unit: 3,
    title: LOP4_UNIT_TITLES[3],
    words: [
      { word: "Monday", hint: "thứ Hai", ipa: "/ˈmʌndeɪ/" },
      { word: "Tuesday", hint: "thứ Ba", ipa: "/ˈtjuːzdeɪ/" },
      { word: "Wednesday", hint: "thứ Tư", ipa: "/ˈwenzdeɪ/" },
      { word: "Thursday", hint: "thứ Năm", ipa: "/ˈθɜːzdeɪ/" },
      { word: "Friday", hint: "thứ Sáu", ipa: "/ˈfraɪdeɪ/" },
      { word: "Saturday", hint: "thứ Bảy", ipa: "/ˈsætədeɪ/" },
      { word: "Sunday", hint: "chủ nhật", ipa: "/ˈsʌndeɪ/" },
      { word: "week", hint: "tuần", ipa: "/wiːk/" },
      { word: "day", hint: "ngày", ipa: "/deɪ/" },
      { word: "every day", hint: "mỗi ngày", ipa: "/ˈevri deɪ/" },
      { word: "have English", hint: "học Tiếng Anh", ipa: "/hæv ˈɪŋɡlɪʃ/" },
      { word: "have PE", hint: "học Thể dục", ipa: "/hæv ˌpiː ˈiː/" },
      { word: "have music", hint: "học Âm nhạc", ipa: "/hæv ˈmjuːzɪk/" },
      { word: "have art", hint: "học Mỹ thuật", ipa: "/hæv ɑːt/" },
      { word: "clean my room", hint: "dọn phòng", ipa: "/kliːn maɪ ruːm/" },
      { word: "play football", hint: "chơi bóng đá", ipa: "/pleɪ ˈfʊtbɔːl/" },
      { word: "play badminton", hint: "chơi cầu lông", ipa: "/pleɪ ˈbædmɪntən/" },
      { word: "read books", hint: "đọc sách", ipa: "/riːd bʊks/" },
      { word: "watch TV", hint: "xem ti vi", ipa: "/wɒtʃ ˌtiːˈviː/" },
      { word: "on the weekend", hint: "vào cuối tuần", ipa: "/ɒn ðə ˌwiːkˈend/" },
    ],
  },
  4: {
    unit: 4,
    title: LOP4_UNIT_TITLES[4],
    words: [
      { word: "birthday", hint: "sinh nhật", ipa: "/ˈbɜːθdeɪ/" },
      { word: "party", hint: "bữa tiệc", ipa: "/ˈpɑːtiː/" },
      { word: "invite", hint: "mời", ipa: "/ɪnˈvaɪt/" },
      { word: "guest", hint: "khách mời", ipa: "/ɡest/" },
      { word: "present", hint: "món quà", ipa: "/ˈprezʌnt/" },
      { word: "gift", hint: "món quà", ipa: "/ɡɪft/" },
      { word: "balloon", hint: "quả bóng bay", ipa: "/bəˈluːn/" },
      { word: "cake", hint: "bánh kem", ipa: "/keɪk/" },
      { word: "food", hint: "đồ ăn", ipa: "/fuːd/" },
      { word: "drink", hint: "đồ uống", ipa: "/drɪŋk/" },
      { word: "decorate", hint: "trang trí", ipa: "/ˈdekɜːeɪt/" },
      { word: "make a wish", hint: "ước điều ước", ipa: "/meɪk ə wɪʃ/" },
      { word: "blow out", hint: "thổi tắt", ipa: "/bləʊ aʊt/" },
      { word: "sing", hint: "hát", ipa: "/sɪŋ/" },
      { word: "play games", hint: "chơi trò chơi", ipa: "/pleɪ ɡeɪmz/" },
      { word: "take photos", hint: "chụp ảnh", ipa: "/teɪk ˈfəʊtəʊz/" },
      { word: "fun", hint: "vui vẻ, thú vị", ipa: "/fʌn/" },
      { word: "thanks", hint: "cảm ơn", ipa: "/θæŋks/" },
      { word: "enjoy", hint: "thích thú, tận hưởng", ipa: "/ɪnˈdʒɔɪ/" },
      { word: "have a great time", hint: "có khoảng thời gian tuyệt vời", ipa: "/hæv ə ɡreɪt taɪm/" },
    ],
  },
  5: {
    unit: 5,
    title: LOP4_UNIT_TITLES[5],
    words: [
      { word: "can", hint: "có thể", ipa: "/kæn/" },
      { word: "cook", hint: "nấu ăn", ipa: "/kʊk/" },
      { word: "draw", hint: "vẽ", ipa: "/drɔː/" },
      { word: "play the guitar", hint: "chơi đàn ghi-ta", ipa: "/pleɪ ðə ɡɪˈtɑː(r)/" },
      { word: "play the piano", hint: "chơi đàn pi-a-nô", ipa: "/pleɪ ðə piˈænəʊ/" },
      { word: "ride a bike", hint: "đi xe đạp", ipa: "/raɪd ə baɪk/" },
      { word: "ride a horse", hint: "cưỡi ngựa", ipa: "/raɪd ə hɔːs/" },
      { word: "swim", hint: "bơi", ipa: "/swɪm/" },
      { word: "roller skate", hint: "trượt pa-tin", ipa: "/ˈrəʊlɜː skeɪt/" },
      { word: "play football", hint: "chơi bóng đá", ipa: "/pleɪ ˈfʊtbɔːl/" },
      { word: "play badminton", hint: "chơi cầu lông", ipa: "/pleɪ ˈbædmɪntən/" },
      { word: "fly a kite", hint: "thả diều", ipa: "/flaɪ ə kaɪt/" },
      { word: "sing", hint: "hát", ipa: "/sɪŋ/" },
      { word: "dance", hint: "nhảy múa", ipa: "/dɑːns/" },
      { word: "plant trees", hint: "trồng cây", ipa: "/plɑːnt triːz/" },
      { word: "help parents", hint: "giúp bố mẹ", ipa: "/help ˈpeərənts/" },
      { word: "clean the room", hint: "dọn phòng", ipa: "/kliːn ðə ruːm/" },
      { word: "read books", hint: "đọc sách", ipa: "/riːd bʊks/" },
      { word: "take photos", hint: "chụp ảnh", ipa: "/teɪk ˈfəʊtəʊz/" },
      { word: "watch TV", hint: "xem ti vi", ipa: "/wɒtʃ ˌtiːˈviː/" },
    ],
  },
  6: {
    unit: 6,
    title: LOP4_UNIT_TITLES[6],
    words: [
      { word: "school", hint: "trường học", ipa: "/skuːl/" },
      { word: "classroom", hint: "phòng học", ipa: "/ˈklɑːsruːm/" },
      { word: "library", hint: "thư viện", ipa: "/ˈlaɪbrəri/" },
      { word: "playground", hint: "sân chơi", ipa: "/ˈpleɪɡraʊnd/" },
      { word: "computer room", hint: "phòng máy tính", ipa: "/kəmˈpjuːtə ruːm/" },
      { word: "music room", hint: "phòng âm nhạc", ipa: "/ˈmjuːzɪk ruːm/" },
      { word: "art room", hint: "phòng mỹ thuật", ipa: "/ɑːt ruːm/" },
      { word: "science room", hint: "phòng khoa học", ipa: "/ˈsaɪəns ruːm/" },
      { word: "gym", hint: "phòng thể chất", ipa: "/dʒɪm/" },
      { word: "canteen", hint: "nhà ăn", ipa: "/kæˈntiːn/" },
      { word: "toilet", hint: "nhà vệ sinh", ipa: "/ˈtɔɪlʌt/" },
      { word: "garden", hint: "vườn", ipa: "/ˈɡɑːdn/" },
      { word: "gate", hint: "cổng trường", ipa: "/ɡeɪt/" },
      { word: "stairs", hint: "cầu thang", ipa: "/sterz/" },
      { word: "corridor", hint: "hành lang", ipa: "/ˈkɒrʌdɜː/" },
      { word: "classmate", hint: "bạn cùng lớp", ipa: "/ˈklæsmeɪt/" },
      { word: "teacher", hint: "giáo viên", ipa: "/ˈtiːtʃə/" },
      { word: "blackboard", hint: "bảng đen", ipa: "/ˈblækbɒrd/" },
      { word: "desk", hint: "bàn", ipa: "/desk/" },
      { word: "chair", hint: "ghế", ipa: "/tʃeə(r)/" },
    ],
  },
  7: {
    unit: 7,
    title: LOP4_UNIT_TITLES[7],
    words: [
      { word: "art", hint: "Mỹ thuật", ipa: "/ɑːt/" },
      { word: "English", hint: "Tiếng Anh", ipa: "/ˈɪŋɡlɪʃ/" },
      { word: "history and geography", hint: "Lịch sử và Địa lí", ipa: "/ˈhɪstri ənd dʒiˈɒɡrəfi/" },
      { word: "maths", hint: "Toán", ipa: "/mæθs/" },
      { word: "music", hint: "Âm nhạc", ipa: "/ˈmjuːzɪk/" },
      { word: "science", hint: "Khoa học", ipa: "/ˈsaɪʌns/" },
      { word: "Vietnamese", hint: "Tiếng Việt", ipa: "/ˌvjetnəˈmiːz/" },
      { word: "Monday", hint: "Thứ Hai", ipa: "/ˈmʌndeɪ/" },
      { word: "Tuesday", hint: "Thứ Ba", ipa: "/ˈtjuːzdeɪ/" },
      { word: "Wednesday", hint: "Thứ Tư", ipa: "/ˈwenzdeɪ/" },
      { word: "Thursday", hint: "Thứ Năm", ipa: "/ˈθɜːzdeɪ/" },
      { word: "Friday", hint: "Thứ Sáu", ipa: "/ˈfraɪdeɪ/" },
      { word: "timetable", hint: "thời khóa biểu", ipa: "/ˈtaɪmteɪbʌl/" },
      { word: "subject", hint: "môn học", ipa: "/sʌbdʒˈekt/" },
      { word: "lesson", hint: "tiết học", ipa: "/ˈlesʌn/" },
      { word: "have English", hint: "học Tiếng Anh", ipa: "/hæv ˈɪŋɡlɪʃ/" },
      { word: "have Maths", hint: "học Toán", ipa: "/hæv mæθs/" },
      { word: "have Music", hint: "học Âm nhạc", ipa: "/hæv ˈmjuːzɪk/" },
      { word: "have Science", hint: "học Khoa học", ipa: "/hæv ˈsaɪəns/" },
      { word: "have Art", hint: "học Mỹ thuật", ipa: "/hæv ɑːt/" },
    ],
  },
  8: {
    unit: 8,
    title: LOP4_UNIT_TITLES[8],
    words: [
      { word: "IT", hint: "Công nghệ thông tin", ipa: "/ˌaɪ ˈtiː/" },
      { word: "PE", hint: "Thể dục", ipa: "/ˌpiː ˈiː/" },
      { word: "English teacher", hint: "giáo viên Tiếng Anh", ipa: "/ˈɪŋɡlɪʃ ˈtiːtʃə(r)/" },
      { word: "painter", hint: "họa sĩ", ipa: "/ˈpeɪntɜː/" },
      { word: "maths teacher", hint: "giáo viên Toán", ipa: "/mæθs ˈtiːtʃə(r)/" },
      { word: "writer", hint: "nhà văn", ipa: "/ˈraɪtə/" },
      { word: "because", hint: "bởi vì", ipa: "/bɪˈkɒz/" },
      { word: "why", hint: "tại sao", ipa: "/wˈaɪ/" },
      { word: "like", hint: "thích", ipa: "/laɪk/" },
      { word: "write", hint: "viết", ipa: "/raɪt/" },
      { word: "read", hint: "đọc", ipa: "/riːd/" },
      { word: "draw", hint: "vẽ", ipa: "/drɔː/" },
      { word: "play sports", hint: "chơi thể thao", ipa: "/pleɪ spɔːts/" },
      { word: "computer", hint: "máy tính", ipa: "/kʌˈmpjuːtɜː/" },
      { word: "lesson", hint: "tiết học", ipa: "/ˈlesʌn/" },
      { word: "interesting", hint: "thú vị", ipa: "/ˈɪntrəstɪŋ/" },
      { word: "fun", hint: "vui", ipa: "/fʌn/" },
      { word: "useful", hint: "hữu ích", ipa: "/ˈjuːsfl/" },
      { word: "favourite", hint: "yêu thích nhất", ipa: "/ˈfeɪvərɪt/" },
      { word: "subject", hint: "môn học", ipa: "/sʌbdʒˈekt/" },
    ],
  },
  9: {
    unit: 9,
    title: LOP4_UNIT_TITLES[9],
    words: [
      { word: "December", hint: "tháng Mười hai", ipa: "/dɪˈsembɜː/" },
      { word: "June", hint: "tháng Sáu", ipa: "/dʒˈuːn/" },
      { word: "July", hint: "tháng Bảy", ipa: "/dʒuːˈlaɪ/" },
      { word: "November", hint: "tháng Mười một", ipa: "/nəʊˈvembɜː/" },
      { word: "October", hint: "tháng Mười", ipa: "/ɒkˈtəʊbə(r)/" },
      { word: "September", hint: "tháng Chín", ipa: "/seˈptembɜː/" },
      { word: "sports day", hint: "ngày hội thể thao", ipa: "/spɔːts deɪ/" },
      { word: "run", hint: "chạy", ipa: "/rʌn/" },
      { word: "jump", hint: "nhảy", ipa: "/dʒˈʌmp/" },
      { word: "throw", hint: "ném", ipa: "/θrəʊ/" },
      { word: "race", hint: "cuộc đua", ipa: "/reɪs/" },
      { word: "team", hint: "đội", ipa: "/tiːm/" },
      { word: "tug of war", hint: "kéo co", ipa: "/ˌtʌɡ əv ˈwɔː(r)/" },
      { word: "prize", hint: "giải thưởng", ipa: "/praɪz/" },
      { word: "cheer", hint: "cổ vũ", ipa: "/tʃˈɪr/" },
      { word: "when", hint: "khi nào", ipa: "/wˈen/" },
      { word: "is", hint: "là", ipa: "/ɪz/" },
      { word: "it", hint: "nó", ipa: "/ɪt/" },
      { word: "isn't", hint: "không phải là", ipa: "/ˈɪznt/" },
      { word: "isn't it", hint: "không phải sao", ipa: "/ˈɪznt ɪt/" },
    ],
  },
  10: {
    unit: 10,
    title: LOP4_UNIT_TITLES[10],
    words: [
      { word: "beach", hint: "bãi biển", ipa: "/biːtʃ/" },
      { word: "campsite", hint: "khu cắm trại", ipa: "/ˈkæmpsaɪt/" },
      { word: "countryside", hint: "nông thôn", ipa: "/ˈkʌntrisaɪd/" },
      { word: "Bangkok", hint: "Băng Cốc", ipa: "/ˈbæŋkɒk/" },
      { word: "London", hint: "Luân Đôn", ipa: "/ˈlʌndən/" },
      { word: "Sydney", hint: "Xi-đni", ipa: "/ˈsɪdni/" },
      { word: "Tokyo", hint: "Tô-ki-ô", ipa: "/ˈtəʊkiəʊ/" },
      { word: "last", hint: "trước đây", ipa: "/læst/" },
      { word: "yesterday", hint: "hôm qua", ipa: "/ˈjestɜːdeɪ/" },
      { word: "at", hint: "tại, ở", ipa: "/æt/" },
      { word: "on", hint: "vào", ipa: "/ɒn/" },
      { word: "in", hint: "trong", ipa: "/ɪn/" },
      { word: "was", hint: "đã là", ipa: "/wˈɑːz/" },
      { word: "were", hint: "đã là", ipa: "/wˈɜː/" },
      { word: "where", hint: "ở đâu", ipa: "/wˈer/" },
      { word: "come back", hint: "trở về", ipa: "/kʌm bæk/" },
      { word: "visit", hint: "thăm", ipa: "/ˈvɪzɪt/" },
      { word: "go swimming", hint: "đi bơi", ipa: "/ɡəʊ ˈswɪmɪŋ/" },
      { word: "go camping", hint: "đi cắm trại", ipa: "/ɡəʊ ˈkæmpɪŋ/" },
      { word: "have a great time", hint: "có khoảng thời gian tuyệt vời", ipa: "/hæv ə ɡreɪt taɪm/" },
    ],
  },
  11: {
    unit: 11,
    title: LOP4_UNIT_TITLES[11],
    words: [
      { word: "live", hint: "sống", ipa: "/laɪv/" },
      { word: "street", hint: "đường phố", ipa: "/striːt/" },
      { word: "road", hint: "con đường", ipa: "/roʊd/" },
      { word: "in", hint: "trong, ở", ipa: "/ɪn/" },
      { word: "at", hint: "tại (số nhà)", ipa: "/æt/" },
      { word: "a busy street", hint: "một con đường nhộn nhịp", ipa: "/ə ˈbɪzi striːt/" },
      { word: "a quiet village", hint: "một ngôi làng yên tĩnh", ipa: "/ə ˈkwaɪət ˈvɪlɪdʒ/" },
      { word: "a noisy road", hint: "một con đường ồn ào", ipa: "/ə ˈnɔɪzi rəʊd/" },
      { word: "a big city", hint: "một thành phố lớn", ipa: "/ə bɪɡ ˈsɪti/" },
    ],
  },
  12: {
    unit: 12,
    title: LOP4_UNIT_TITLES[12],
    words: [
      { word: "farmer", hint: "nông dân", ipa: "/ˈfɑːmə(r)/" },
      { word: "policeman", hint: "cảnh sát", ipa: "/pʌˈliːsmʌn/" },
      { word: "office worker", hint: "nhân viên văn phòng", ipa: "/ˈɒfɪs ˌwɜːkə(r)/" },
      { word: "actor", hint: "diễn viên", ipa: "/ˈæktə(r)/" },
      { word: "nurse", hint: "y tá", ipa: "/nɜːs/" },
      { word: "nursing home", hint: "viện điều dưỡng", ipa: "/ˈnɜːsɪŋ həʊm/" },
      { word: "factory", hint: "nhà máy", ipa: "/ˈfæktɜːiː/" },
      { word: "school", hint: "trường học", ipa: "/skuːl/" },
      { word: "farm", hint: "nông trại", ipa: "/fɑːm/" },
      { word: "hospital", hint: "bệnh viện", ipa: "/ˈhɑːspɪtʌl/" },
    ],
  },
  13: {
    unit: 13,
    title: LOP4_UNIT_TITLES[13],
    words: [
      { word: "look like", hint: "trông như thế nào", ipa: "/lʊk laɪk/" },
      { word: "tall", hint: "cao", ipa: "/tɒl/" },
      { word: "short", hint: "thấp", ipa: "/ʃˈɒrt/" },
      { word: "slim", hint: "mảnh khảnh", ipa: "/slɪm/" },
      { word: "short hair", hint: "tóc ngắn", ipa: "/ʃɔːt heə(r)/" },
      { word: "long hair", hint: "tóc dài", ipa: "/lɒŋ heə(r)/" },
      { word: "round face", hint: "khuôn mặt tròn", ipa: "/raʊnd feɪs/" },
      { word: "big eyes", hint: "mắt to", ipa: "/bɪɡ aɪz/" },
    ],
  },
  14: {
    unit: 14,
    title: LOP4_UNIT_TITLES[14],
    words: [
      { word: "in the morning", hint: "vào buổi sáng", ipa: "/ɪn ðə ˈmɔːnɪŋ/" },
      { word: "in the afternoon", hint: "vào buổi chiều", ipa: "/ɪn ði ˌɑːftəˈnuːn/" },
      { word: "at noon", hint: "vào buổi trưa", ipa: "/æt nuːn/" },
      { word: "in the evening", hint: "vào buổi tối", ipa: "/ɪn ði ˈiːvnɪŋ/" },
      { word: "do housework", hint: "làm việc nhà", ipa: "/duː ˈhaʊswɜːk/" },
      { word: "watch TV", hint: "xem ti vi", ipa: "/wɒtʃ ˌtiːˈviː/" },
      { word: "wash the clothes", hint: "giặt áo quần", ipa: "/wɒʃ ðə kləʊðz/" },
      { word: "clean the floor", hint: "lau nhà", ipa: "/kliːn ðə flɔː(r)/" },
      { word: "help with the cooking", hint: "giúp đỡ việc nấu ăn", ipa: "/help wɪð ðə ˈkʊkɪŋ/" },
      { word: "wash the dishes", hint: "rửa chén, bát", ipa: "/wɒʃ ðə ˈdɪʃɪz/" },
    ],
  },
  15: {
    unit: 15,
    title: LOP4_UNIT_TITLES[15],
    words: [
      { word: "gym", hint: "phòng tập gym", ipa: "/dʒɪm/" },
      { word: "shopping centre", hint: "trung tâm mua sắm", ipa: "/ˈʃɒpɪŋ ˌsentə/" },
      { word: "sports centre", hint: "trung tâm thể thao", ipa: "/spɔːts ˌsentə/" },
      { word: "swimming pool", hint: "hồ bơi", ipa: "/ˈswɪmɪŋ puːl/" },
      { word: "cinema", hint: "rạp chiếu phim", ipa: "/ˈsɪnʌmʌ/" },
      { word: "a lot of", hint: "nhiều", ipa: "/ə lɒt əv/" },
      { word: "cook meals", hint: "nấu ăn", ipa: "/kʊk miːlz/" },
      { word: "play tennis", hint: "chơi quần vợt", ipa: "/pleɪ ˈtenɪs/" },
      { word: "watch films", hint: "xem phim", ipa: "/wɒtʃ fɪlmz/" },
      { word: "do yoga", hint: "tập yo-ga", ipa: "/duː ˈjəʊɡə/" },
      { word: "stay at home", hint: "ở nhà", ipa: "/steɪ æt həʊm/" },
      { word: "together", hint: "cùng nhau", ipa: "/tʌˈɡeðɜː/" },
    ],
  },
  16: {
    unit: 16,
    title: LOP4_UNIT_TITLES[16],
    words: [
      { word: "weather", hint: "thời tiết", ipa: "/wˈeðɜː/" },
      { word: "last weekend", hint: "cuối tuần vừa qua", ipa: "/lɑːst ˌwiːkˈend/" },
      { word: "yesterday", hint: "ngày hôm qua", ipa: "/ˈjestɜːdeɪ/" },
      { word: "sunny", hint: "có nắng", ipa: "/ˈsʌniː/" },
      { word: "rainy", hint: "có mưa", ipa: "/ˈreɪniː/" },
      { word: "windy", hint: "có gió", ipa: "/wˈɪndiː/" },
      { word: "cloudy", hint: "có mây", ipa: "/ˈklaʊdiː/" },
      { word: "food stall", hint: "quầy hàng thực phẩm", ipa: "/fuːd stɔːl/" },
      { word: "bookshop", hint: "hiệu sách", ipa: "/ˈbʊkʃɒp/" },
      { word: "supermarket", hint: "siêu thị", ipa: "/ˈsuːpɜːmɑːkɪt/" },
      { word: "bakery", hint: "hiệu bánh", ipa: "/ˈbeɪkɜːiː/" },
      { word: "water park", hint: "công viên nước", ipa: "/ˈwɔːtə pɑːk/" },
      { word: "lovely", hint: "vui vẻ, đáng yêu", ipa: "/ˈlʌvliː/" },
      { word: "great", hint: "tuyệt vời", ipa: "/ɡreɪt/" },
    ],
  },
  17: {
    unit: 17,
    title: LOP4_UNIT_TITLES[17],
    words: [
      { word: "stop", hint: "dừng lại", ipa: "/stɑːp/" },
      { word: "go", hint: "đi", ipa: "/ɡəʊ/" },
      { word: "turn right", hint: "rẽ phải", ipa: "/tɜːn raɪt/" },
      { word: "turn left", hint: "rẽ trái", ipa: "/tɜːn left/" },
      { word: "buy", hint: "mua", ipa: "/baɪ/" },
      { word: "go straight", hint: "đi thẳng", ipa: "/ɡəʊ streɪt/" },
      { word: "turn round", hint: "quay ngược lại", ipa: "/tɜːn raʊnd/" },
      { word: "get to", hint: "đến (địa điểm)", ipa: "/ɡet tuː/" },
      { word: "on the left", hint: "bên trái", ipa: "/ɒn ðə left/" },
      { word: "on the right", hint: "bên phải", ipa: "/ɒn ðə raɪt/" },
    ],
  },
  18: {
    unit: 18,
    title: LOP4_UNIT_TITLES[18],
    words: [
      { word: "near", hint: "gần", ipa: "/nɪə/" },
      { word: "opposite", hint: "đối diện", ipa: "/ˈɒpəzɪt/" },
      { word: "behind", hint: "phía sau", ipa: "/bɪˈhaɪnd/" },
      { word: "between", hint: "ở giữa", ipa: "/bɪtwˈiːn/" },
      { word: "excuse me", hint: "xin lỗi (để hỏi thăm)", ipa: "/ɪkˈskjuːs miː/" },
      { word: "toy shop", hint: "cửa hàng đồ chơi", ipa: "/tɔɪ ʃɒp/" },
      { word: "skirt", hint: "chân váy", ipa: "/skɜːt/" },
      { word: "T-shirt", hint: "áo thun", ipa: "/ˈtiː ʃɜːt/" },
      { word: "gift shop", hint: "cửa hàng quà tặng", ipa: "/ɡɪft ʃɒp/" },
      { word: "thousand", hint: "nghìn", ipa: "/ˈθaʊzʌnd/" },
      { word: "shoe shop", hint: "hiệu giày", ipa: "/ʃuː ʃɒp/" },
      { word: "ice-cream", hint: "kem", ipa: "/ˈaɪskriːm/" },
      { word: "bookshop", hint: "hiệu sách", ipa: "/ˈbʊkʃɒp/" },
      { word: "bakery", hint: "tiệm bánh", ipa: "/ˈbeɪkɜːiː/" },
    ],
  },
  19: {
    unit: 19,
    title: LOP4_UNIT_TITLES[19],
    words: [
      { word: "giraffes", hint: "hươu cao cổ", ipa: "/dʒəˈrɑːfs/" },
      { word: "lions", hint: "sư tử", ipa: "/ˈlaɪʌnz/" },
      { word: "crocodiles", hint: "cá sấu", ipa: "/ˈkrɒkədaɪlz/" },
      { word: "hippos", hint: "hà mã", ipa: "/ˈhɪpəʊz/" },
      { word: "peacocks", hint: "con công", ipa: "/ˈpiːkɒks/" },
      { word: "dance beautifully", hint: "nhảy/múa đẹp", ipa: "/dɑːns ˈbjuːtɪfli/" },
      { word: "run quickly", hint: "chạy nhanh", ipa: "/rʌn ˈkwɪkli/" },
      { word: "roar loudly", hint: "gầm to", ipa: "/rɔː ˈlaʊdli/" },
      { word: "sing merrily", hint: "hát hay", ipa: "/sɪŋ ˈmerɪli/" },
      { word: "neck", hint: "cái cổ", ipa: "/nek/" },
    ],
  },
};

export function getLop4UnitVocab(unit: number): Lop4UnitVocab {
  const data = LOP4_UNIT_VOCAB[unit];
  if (!data) throw new Error(`Unknown Lớp 4 vocab unit: ${unit}`);
  return data;
}

export function slugifyLop4Word(word: string): string {
  return word
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}
